### ISSUE TITLE
Checkpoint 1

### ISSUE THREAD

**Issue by jonesna213** [jonesna213/IndividualProject#1]
@pawaitemadisoncollege Checkpoint 1 is ready for review

**Comment by pawaitemadisoncollege** [comment]
Hi @jonesna213 You have a great start on your indie project!!!  Your deliverables for checkpoint 1 do a thorough job explaining the direction of your project and it's clear you've put in some good time and effort into this already. 

See below for my comments and questions.

**Problem statement**
- [ ] Could be improved by explaining the problem you are solving. Are you a Honda Civic owner who enjoys looking for parts, but currently available sites didn't always provide what you wanted? 
- [ ] I worry a little bit about how some prospective employers might interpret this: 

> This project doesn't have any real purpose


**Project Technologies/Techniques**

- [ ] Rather than Tomcat's JDBC Realm Authentication, we'll be using Amazon's Cognito this semester
- [ ] Might be nice to include the versions of the tools and libraries that you are using (you may not know these yet, but be sure to add them later). This way an prospective employer can that you are using current tech.

**Screen Designs**

These do an excellent job communicating the design of your application. No nitpicks here at all. Know that AWS Cognito can provide the sign-up/sign in dialogs so you likely won't need to create pages for those (just in case you were starting to build jsps already). 

**Project Plan**

- [ ] Depending how you work best, consider listing specific user stories in the plan and include when you will start each story and when you are targeting finishing it.  
- [ ] It may helpful to break down the individual stories into tasks and list those in the plan or put them into a tool like Trello. Again, this depends on how you like to plan and work. 
- [ ] If you already have a system that works well for you, ignore the items above. 

**User Stories**

I think the scope here is doable and covers the key objectives for the ent java project. Well done!

**RESTful service or API integration** 

1. I think Google has a reCaptcha service that's worth exploring.
2. You are right, there is a fitment api here: https://www.programmableweb.com/api/wheel-fitment-rest-api-v10. 
4. Another option could be using one of the many? VIN apis to get vehicle info. 
5.  If there isn't a service to do exactly what you want, you can write your own.  How? Use a library like JSoup to scrape a site like https://www.rockauto.com/en/parts/honda to create your own service. Several students have done something like this as part a team project, and then used the team project service in their indie project. 
6. For hosting parts images, you might consider using Amazon's S3 service. There are lots of tutorial out there;  here is just one of them: https://www.baeldung.com/aws-s3-java

I'm excited to see progress on this! Happy coding!!!
